mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:29:59.134215462Z caller=resolver.go:87 level=error msg="failed to lookup IP addresses" host=mimir-distributed-gossip-ring.mimir.svc.cluster.local. err="lookup mimir-distributed-gossip-ring.mimir.svc.cluster.local. on 34.118.224.10:53: no such host"
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:29:59.136149972Z caller=resolver.go:87 level=error msg="failed to lookup IP addresses" host=mimir-distributed-gossip-ring.mimir.svc.cluster.local. err="lookup mimir-distributed-gossip-ring.mimir.svc.cluster.local. on 34.118.224.10:53: no such host"
mimir-distributed-compactor-0 compactor ts=2024-11-04T06:31:15.138072575Z caller=updater.go:138 level=info component=cleaner run_id=1730701874 task=clean_up_users user=anonymous msg="fetched blocks metas for newly discovered blocks" total_blocks=4 partial_errors=0
mimir-distributed-compactor-0 compactor ts=2024-11-04T06:31:15.165438303Z caller=updater.go:138 level=info component=cleaner run_id=1730701874 task=clean_up_users user=1 msg="fetched blocks metas for newly discovered blocks" total_blocks=29 partial_errors=0
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:00.183943955Z caller=resolver.go:87 level=error msg="failed to lookup IP addresses" host=mimir-distributed-gossip-ring.mimir.svc.cluster.local. err="lookup mimir-distributed-gossip-ring.mimir.svc.cluster.local. on 34.118.224.10:53: no such host"
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:48.987046303Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.106, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:30:00.88Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:49.149295712Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:29:57.468Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:54.057327506Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.106, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:30:15.88Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:54.222002045Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:30:12.468Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:54.750404971Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.106, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:30:02.814Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:55.172946434Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:30:07.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:30:57.446238798Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.106, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:30:23.506Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:31:10.304412415Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:31:07.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:31:25.439094523Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:31:22.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:31:40.570831429Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:31:37.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:31:55.702420837Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:31:52.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-querier-78bc7dd447-tqh6q querier ts=2024-11-04T06:29:59.092967634Z caller=resolver.go:87 level=error msg="failed to lookup IP addresses" host=mimir-distributed-gossip-ring.mimir.svc.cluster.local. err="lookup mimir-distributed-gossip-ring.mimir.svc.cluster.local. on 34.118.224.10:53: no such host"
mimir-distributed-querier-78bc7dd447-tqh6q querier ts=2024-11-04T06:29:59.094395824Z caller=resolver.go:87 level=error msg="failed to lookup IP addresses" host=mimir-distributed-gossip-ring.mimir.svc.cluster.local. err="lookup mimir-distributed-gossip-ring.mimir.svc.cluster.local. on 34.118.224.10:53: no such host"
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:32:10.837246163Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:32:07.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:32:25.971031323Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:32:22.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:32:41.108396766Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:32:37.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:32:56.240710857Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-2: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:32:52.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:33:11.376193447Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:33:07.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-distributor-d7bc74b6f-zdwvm distributor ts=2024-11-04T06:33:26.551701684Z caller=push.go:211 level=error user=1 sourceIPs="10.80.0.68, 10.136.0.11" msg="detected an error while ingesting Prometheus remote-write request (the request may have been partially ingested)" httpCode=400 err="send data to ingesters: failed pushing to ingester mimir-distributed-ingester-1: user=1: the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order). The affected sample has timestamp 2024-11-04T06:33:22.071Z and is from series process_start_time_seconds{instance=\"alloy.internal:12345\", job=\"integrations/agent-check\"} (sampled 1/10)" insight=true
mimir-distributed-querier-78bc7dd447-tqh6q querier ts=2024-11-04T06:30:00.274199639Z caller=resolver.go:87 level=error msg="failed to lookup IP addresses" host=mimir-distributed-gossip-ring.mimir.svc.cluster.local. err="lookup mimir-distributed-gossip-ring.mimir.svc.cluster.local. on 34.118.224.10:53: no such host"
mimir-distributed-querier-78bc7dd447-tqh6q querier ts=2024-11-04T06:30:02.963037098Z caller=resolver.go:87 level=error msg="failed to lookup IP addresses" host=mimir-distributed-gossip-ring.mimir.svc.cluster.local. err="lookup mimir-distributed-gossip-ring.mimir.svc.cluster.local. on 34.118.224.10:53: no such host"
mimir-distributed-querier-78bc7dd447-tqh6q querier ts=2024-11-04T06:30:10.116473814Z caller=scheduler_processor.go:141 level=warn msg="error contacting scheduler" err="rpc error: code = Canceled desc = received context error while waiting for new LB policy update: context canceled" addr=10.136.0.13:9095
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:21 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:22 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:23 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:23 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:23 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:24 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:24 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:24 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "GET /prometheus/api/v1/label/cluster/values?match%5B%5D=up%7Bjob!%3D%22%22%7D&start=1730700024&end=1730701824 HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/label/cluster/values?match%5B%5D=up%7Bjob!%3D%22%22%7D&start=1730700024&end=1730701824", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:25 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:25 [error] 10#10: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:25 [error] 11#11: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:26 [error] 10#10: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:26 [error] 11#11: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:26 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:27 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:27 [error] 14#14: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:27 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:28 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:28 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:28 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:29 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:29 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:29 [error] 11#11: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query_range HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query_range", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:29 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:30 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:31 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:32 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:32 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:32 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:33 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:33 [error] 10#10: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query_range HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query_range", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:33 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:33 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:34 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:34 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:35 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:35 [error] 13#13: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.136.3.18, server: , request: "POST /prometheus/api/v1/query HTTP/1.1", upstream: "http://34.118.229.6:8080/prometheus/api/v1/query", host: "mimir-distributed-nginx.mimir.svc:80"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:37 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:38 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:38 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:38 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:39 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:39 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:39 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:42 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:43 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:43 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:43 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:44 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:44 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:45 [error] 12#12: *4 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:47 [error] 14#14: *2 mimir-distributed-distributor-headless.mimir.svc.cluster.local could not be resolved (3: Host not found), client: 10.136.2.17, server: , request: "POST /api/v1/push HTTP/1.1", host: "platform.mimir.codedge.dev"
mimir-distributed-nginx-555c9d4f99-qswks nginx 2024/11/04 06:30:48 [error] 12#12: *4 mimir-distributed-distri